// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pvcqfotzbntthdlmyefj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB2Y3Fmb3R6Ym50dGhkbG15ZWZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3MDAxMTgsImV4cCI6MjA2NDI3NjExOH0.bN462HJ74ewNBYJwJVRJdZtbRGBAL-uk6Q8g543EVXo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);